# Messages
messages:
  prefix: "&6[PvpSmash]"
  join: "%prefix% &a+ &e%player_name% s'est connecté. &a(%online_players%/%max_players%)"
  quit: "%prefix% &c- &e%player_name% s'est déconnecté. &a(%online_players%/%max_players%)"

# Lobby
lobby:
  spawn:
    world: "pvpsmash_lobby"
    x: 1000.5
    y: 100.0
    z: 9000.5
    yaw: 90
    pitch: 0
  game_start:
    min_players: 2
    countdown: 10
    titles:
      countdown:
        title: "&7Début dans %countdown% seconde(s)"
        subtitle: ""
      started:
        title: "&7Lancement du jeu!"
        subtitle: ""
  scoreboard:
    title: "&6&lFan&f&lCraft&f&o.eu"
    lines:
      - ""
      - "&7Jeu&f: PvpSmash"
      - "&7Joueurs&f: &a%online_players%/&a%max_players%"
      - ""
      - "%game_status%"
      - ""
      - "&7Boost Gloire&f: &6+%glory_boost%%"
      - "&7Boost Points&f: &6+%points_boost%%"
    status_messages:
      waiting: "&cEn attente de joueurs..."
      starting: "&7Début dans &f%countdown%s"
  items:
    return_to_lobby:
      enabled: true
      slot: 8
      name: "&6Retour au lobby"
      material: "DARK_OAK_DOOR_ITEM"
      lore:
        - "&7Cliquez pour retourner au lobby."