messages:
  prefix: "&6[PvpSmash]"
  join: "%prefix% &a+ &e%player_name% s'est connecté. &a(%online_players%/%max_players%)"
  quit: "%prefix% &c- &e%player_name% s'est déconnecté. &a(%online_players%/%max_players%)"

lobby:
  world: "world"
  spawn:
    x: 0.5
    y: 100
    z: 0.5
    yaw: 0.0
    pitch: 0.0